volumes:
  data:
    external: ${VOLUME_EXTERNAL:-false}
    name: ${VOLUME_NAME:-dex_data}
    driver: ${VOLUME_DRIVER:-local}

networks:
  public:
    external: ${PUBLIC_NETWORK_EXTERNAL:-true}
    name: ${PUBLIC_NETWORK_NAME:-traefik-public}
    driver: ${PUBLIC_NETWORK_DRIVER:-overlay}
    attachable: ${PUBLIC_NETWORK_ATTACHABLE:-true}

services:
  dex:
    image: ${IMAGE_NAME:-ghcr.io/dexidp/dex}:${IMAGE_VERSION:-v2.44.0-distroless}
    networks:
      - public
    environment:
      - APP_NAME=${APP_NAME:-dex}
      - BASE_DOMAIN=${BASE_DOMAIN:-localhost}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - GITHUB_ORG=${GITHUB_ORG:-}
      - GITHUB_ORG_2=${GITHUB_ORG_2:-}
      - GITHUB_ORG_3=${GITHUB_ORG_3:-}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_FORMAT=${LOG_FORMAT:-text}
    volumes:
      - data:/data
    deploy:
      labels:
        - "traefik.enable=${TRAEFIK_ENABLE:-true}"
        - "traefik.http.services.dex.loadbalancer.server.port=5556"
        - "traefik.http.routers.dex-http.rule=Host(`${APP_NAME:-dex}.${BASE_DOMAIN:-localhost}`)"
        - "traefik.http.routers.dex-http.entrypoints=${TRAEFIK_HTTP_ENTRYPOINT:-http}"
        - "traefik.http.routers.dex-http.middlewares=${TRAEFIK_HTTP_MIDDLEWARES:-https-redirect}"
        - "traefik.http.routers.dex-http.service=dex"
        - "traefik.http.routers.dex-https.rule=Host(`${APP_NAME:-dex}.${BASE_DOMAIN:-localhost}`)"
        - "traefik.http.routers.dex-https.entrypoints=${TRAEFIK_HTTPS_ENTRYPOINT:-https}"
        - "traefik.http.routers.dex-https.tls=${TRAEFIK_TLS:-true}"
        - "traefik.http.routers.dex-https.tls.certresolver=${TRAEFIK_TLS_RESOLVER:-myresolver}"
        - "traefik.http.routers.dex-https.middlewares=${TRAEFIK_HTTPS_MIDDLEWARES:-}"
        - "traefik.http.routers.dex-https.service=dex"
      replicas: ${REPLICAS:-1}
